### ISSUE TITLE
State variable 

### ISSUE THREAD

**Issue by Felipemendezrios** [BaM-tools/RBaM#6]
The prediction function allows you to manage the state variable, but it only works with a single state variable. In the case of Qmec2, we need to export more than one state variable. Normally, we'd answer the question: Do state prediction? However, you have to answer TRUE several times, as the state variable is and there is no possibility of doing so at the moment. 
Solution: replicate TRUE as many times as file names detected @benRenard .

**Comment by benRenard** [comment]
I'm not sure too see what's going wrong - this seems to be implemented as you request, but I'm certainly missing something. Could you please attach a minimal reproducible example so that I can see the problem more precisely?

**Comment by Felipemendezrios** [comment]
Here an example using the prediction function to generate the file : 

totalU=prediction(X=dat[c('h1','h2')], # stage values
                  spagFiles='totalU.spag', # file where predictions are saved
                  data.dir=workspace, # a copy of data files will be saved here
                  doParametric=TRUE, # propagate parametric uncertainty, i.e. MCMC samples?
                  doStructural=TRUE, # propagate structural uncertainty ?
                  spagFiles_state =c('pressure.spag','friction.spag','advection.spag'),
                  transposeSpag_state = TRUE,
                  envFiles_state = c('pressure.env','friction.env','advection.env')) 

Here the file generated : [Config_Pred_LuhTMK.txt](https://github.com/user-attachments/files/16140755/Config_Pred_LuhTMK.txt)

It does not work because in the line: Do state prediction? (size nState), there is only one TRUE and this would work if the number of state variables were equal to one (BaRatin case). However, in this case (Qmec), three state variables are required. That's why we have to set "TRUE" three times. 

The easiest way to solve this problem is as follows: 
if the user has specified a name, replace FALSE with TRUE as many times as the number of name files

**Comment by benRenard** [comment]
It should be fixed now. I had to make a slight change in BaM as well so you'll need to recompile it. Also note that you can simplify your usage of `prediction` as follows:

```
totalU=prediction(X=dat[c('h1','h2')], # stage values
                  fname = "Config_Pred_TotalU.txt",
                  spagFiles='totalU.spag', # file where predictions are saved
                  data.dir=getwd(), # a copy of data files will be saved here
                  doParametric=TRUE, # propagate parametric uncertainty, i.e. MCMC samples?
                  doStructural=TRUE, # propagate structural uncertainty ?
                  spagFiles_state =c('pressure.spag','friction.spag','advection.spag'))
```

i.e. no need to specify `transposeSpag_state` or `envFiles_state`, default values will take care of that for you (unless you want to change these default values, of course, but I don't see why you would in this case). If you don't specify `spagFiles_state`, state prediction will be skipped

I'm closing the ticket, feel free to re-open if something is still wrong.

**Comment by Felipemendezrios** [comment]
Thanks for debugging, it works fine. However, it seems that in the calibration step, the residual file also exports state variables but with some problems in the column names. I think the character size is not big enough and the tab between names is missing.
 
You can reproduce the file with the MRE. Here an example with the column names :
X1_obs         X2_obs         X1_true        X2_true        Y1_obs         Y1_unbiased    Y1_sim         Y1_res         Y1_stdres      pressure_gradiebottom_frictionadvection

**Comment by benRenard** [comment]
My favorite fix would be to shorten the hard-coded state names in BaM. Could you tell me what good names would be? 

1. advection: ok
2. bottom_friction: I would replace by just friction, ok?
3.  pressure_gradient: pressure? dpressure? dP? Pgradient ?

Let me know what you prefer, or if you want to do it yourself go ahead!

**Comment by Felipemendezrios** [comment]
I think that column names should be clear and the order could be important too. 

1. pressure
2. friction
3. advection

One last question: are column names hard-coded?. In other words, do I have to be careful when defining a state variable to respect the order of pressure, friction and advection?

**Comment by benRenard** [comment]
Yes, you're correct, order is important.

The column names used in the residual files correspond to the state names defined [here](https://github.com/BaM-tools/BaM/blob/137021382d97229c1e995be95bd001cdd6166ea5/src/ModelLibrary_tools.f90#L632). This is the only line you have to change.

The order of the states is defined at [this line](https://github.com/BaM-tools/BaM/blob/137021382d97229c1e995be95bd001cdd6166ea5/src/ModelLibrary_tools.f90#L335). So indeed you need to make sure that state names follow the order defined here - 1. pressure, 2. friction, 3. advection.

**Comment by Felipemendezrios** [comment]
I just committed the new column names to make them shorter. It seems that a size of 15 characters has been hard-coded and that if the column names exceed this size, it will not consider several columns but only one.
I will close the issue, thank you.
